# attribuer un nom au flux de travail.
name: Test pytest and flack8 conttrol push
# Définir l'action sur "push".
on: push 

# ajouter jobs 
jobs:
  qa:
  name: check tests
  runs-on: ubuntu-20.04
  # Maintenant, configurons nos étapes.
  # Nous avons 5 étapes :
  steps: 
  -name: chechout on master
   uses: actions/chekout@v3

   -name: Set -up python 
    uses: actions/setup-python@master
    with:
    python-version: "3.x"

    -name: install pytest and flack8
     run: |
     pip install pytest
     pip install flack8

    -name: Ruen tests
      run: | 
       pytest

      -name: Run flack8
       uses:py-actions/flack8@v2
       